-- Script was generated by Devart Entity Developer, Version 7.2.21.0
-- Script date 2024. 06. 15. 13:57:03
-- Target Server: SQL Server
-- Server Version: 2019

-- 
-- Creating a table dbo.helyseg 
-- 
CREATE TABLE dbo.helyseg (
   id INT NOT NULL IDENTITY,
   IRSZ NVARCHAR(15) NOT NULL,
   nev NVARCHAR(75) NOT NULL,
   CONSTRAINT PK_helyseg PRIMARY KEY (id)
)
GO

-- 
-- Creating a table dbo.felhasznalo 
-- 
CREATE TABLE dbo.felhasznalo (
   id INT NOT NULL IDENTITY,
   nev NVARCHAR(250) NOT NULL,
   email NVARCHAR(100),
   password NVARCHAR(300) NOT NULL,
   CONSTRAINT PK_felhasznalo PRIMARY KEY (id)
)
GO

-- 
-- Creating a table dbo.Szemely 
-- 
CREATE TABLE dbo.Szemely (
   id INT NOT NULL IDENTITY,
   vezeteknev NVARCHAR(100) NOT NULL,
   utonev NVARCHAR(100) NOT NULL,
   lakcim NVARCHAR(100) NOT NULL,
   enHelysegid INT,
   CONSTRAINT PK_Szemely PRIMARY KEY (id),
   CONSTRAINT FK_Szemely_helyseg_0 FOREIGN KEY (enHelysegid) REFERENCES dbo.helyseg (id)
)
GO

-- 
-- Creating a table dbo.telefonszam 
-- 
CREATE TABLE dbo.telefonszam (
   id INT NOT NULL IDENTITY,
   szam NVARCHAR(50) NOT NULL,
   enSzemlyid INT,
   CONSTRAINT PK_telefonszam PRIMARY KEY (id),
   CONSTRAINT FK_telefonszam_Szemely_0 FOREIGN KEY (enSzemlyid) REFERENCES dbo.Szemely (id)
)
GO

